"""Tables for Level A (A.1 Geometry, A.2 Parts, A.3 Kinematics), written to docs/evaluation/results_A.md."""
from __future__ import annotations

import json
from collections import defaultdict

import numpy as np

from ppbench.v2.afford import core
from ppbench.v2.task import RESULTS, ROOT

NAMES = {"claude-fable-5.1": "Claude Fable 5.1", "claude-opus-5": "Claude Opus 5", "claude-sonnet-5": "Claude Sonnet 5",
         "claude-haiku-4.5": "Claude Haiku 4.5", "gpt-6-astra": "GPT-6 Astra", "gpt-5.6-sol": "GPT-5.6 Sol"}
EXCLUDED = {"glm-4.6v-flash", "kimi-vl-a3b-instruct"}     # removed by the owner on 2026-09-21 (tool-use failure)


def _mean(v):
    v = [x for x in v if x is not None]
    return float(np.mean(v)) if v else None


def _f(x, w=5):
    return " " * (w - 1) + "–" if x is None else f"{x:{w}.1f}"


def summarise(rows, tasks_a3):
    out = {}
    by = defaultdict(list)
    for r in rows:
        by[r["system"]].append(r)
    for s, L in by.items():
        size = [r.get("A1_envelope", {}).get("size") for r in L]
        out[s] = {"n": len(L), "tasks": {r["task"] for r in L},
                  "A1": _mean([r["A1"] for r in L]), "A2": _mean([r["A2"] for r in L]),
                  "A3": _mean([r["A3"] for r in L if r["task"] in tasks_a3]),
                  "n3": sum(1 for r in L if r["task"] in tasks_a3 and r["A3"] is not None),
                  "size": _mean([100 * x if x is not None else None for r, x in zip(L, size)]),
                  "empty": sum(1 for r in L if r.get("empty"))}
    return out


def write(rows, tids):
    sheets = {}
    for tid in tids:
        p = RESULTS / tid / "afford" / "sheet.json"
        if p.exists():
            sheets[tid] = json.loads(p.read_text())
    tasks_a3 = {t for t, s in sheets.items() if any(k["scored"] for k in s["kinematics"])}
    llm = [r for r in rows if r.get("family") == "llm" and r["system"] not in EXCLUDED]
    dom = [r for r in rows if r.get("family") == "domain"]
    ref = [r for r in rows if r["key"] == "pop__reference"]
    L = summarise(llm, tasks_a3)
    D = summarise(dom, tasks_a3)
    R = summarise(ref, tasks_a3)
    common = set.intersection(*[v["tasks"] for v in L.values()]) if L else set()
    lines = ["# Level A results: A.1 Geometry, A.2 Parts, A.3 Kinematics (spec A-v1)", "",
             f"Generated by `python -m ppbench.v2.afford.run table`. {len(sheets)} task sheets; "
             f"A.3 is asked on {len(tasks_a3)} tasks (those with a kinematic claim some real instance realises).", ""]

    def table(S, title, paired=None):
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| System | tasks | A.1 Geometry | A.2 Parts | A.3 Kinematics | size (A.1 sub) | mean | empty |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for s, v in sorted(S.items(), key=lambda kv: -(_mean([kv[1]["A1"], kv[1]["A2"], kv[1]["A3"]]) or 0)):
            m = _mean([v["A1"], v["A2"], v["A3"]])
            lines.append(f"| {NAMES.get(s, s)} | {v['n']} | {_f(v['A1'])} | {_f(v['A2'])} | {_f(v['A3'])} (n={v['n3']}) | "
                         f"{_f(v['size'])} | {_f(m)} | {v['empty']} |")
        lines.append("")
    table(R, "Reference object (the task's own real instance, scored against a sheet calibrated without it)")
    table(L, "Tier B — all agent models (main setting: name_only+image, 3 rounds)")
    if common and any(len(v["tasks"]) > len(common) for v in L.values()):
        Lp = summarise([r for r in llm if r["task"] in common], tasks_a3)
        table(Lp, f"Tier B — paired on the {len(common)} tasks every agent has")
    table(D, "Domain-specific generators (main-setting outputs; unitless meshes carry the oracle scale, so their size column is empty)")
    # scoping
    lines += ["## What each task asks", "",
              "| Task | real instances | components scored / claimed | kinematic claims scored / claimed | Wikipedia sizes |",
              "|---|---|---|---|---|"]
    for tid in tids:
        s = sheets.get(tid)
        if not s:
            continue
        cs = [c for c in s["components"]]
        sc = [c["name"] + (f"×{c['count_min']}" if c["count_min"] > 1 else "") for c in cs if c["scored"]]
        ks = [f"{k['id']} {k['moving_phrase']}" for k in s["kinematics"] if k["scored"]]
        ws = [f"{w.get('mapped_to', w['dim'])} {w['min_m']:.2f}–{w['max_m']:.2f} m" for w in s["envelope"].get("wikipedia", [])]
        lines.append(f"| {tid} | {s['n_population']} | {len(sc)}/{len(cs)}: {', '.join(sc)} | {len(ks)}/{len(s['kinematics'])}: "
                     f"{', '.join(ks)} | {'; '.join(ws)} |")
    lines.append("")
    out = ROOT / "docs/evaluation/results_A.md"
    out.write_text("\n".join(lines) + "\n")
    js = {"llm": {k: {**v, "tasks": sorted(v["tasks"])} for k, v in L.items()},
          "domain": {k: {**v, "tasks": sorted(v["tasks"])} for k, v in D.items()},
          "reference": {k: {**v, "tasks": sorted(v["tasks"])} for k, v in R.items()},
          "tasks_a3": sorted(tasks_a3), "common": sorted(common)}
    (RESULTS / "_afford" / "summary.json").write_text(json.dumps(js, indent=1, default=float))
    print("\n".join(lines[:80]))
